# Generated by Django 2.1.5 on 2019-02-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=500)),
                ('job_slug', models.CharField(max_length=700)),
                ('job_name_id', models.IntegerField()),
                ('job_location_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_remote_friendly', models.BooleanField(default=False)),
                ('job_description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.CompanyDetails')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_skill_id', models.CharField(max_length=10)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.JobPost')),
            ],
        ),
    ]
