# Generated by Django 2.1.5 on 2019-02-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_jobpost_jobskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
