# Generated by Django 2.1.5 on 2019-02-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_jobpost_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_email', models.CharField(max_length=200)),
                ('applied_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobapplicants',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.JobPost'),
        ),
    ]
