# Generated by Django 2.1.5 on 2019-02-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_auto_20190222_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='added_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
