# Generated by Django 2.1.5 on 2019-03-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_homerecruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsByRecruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.HomeRecruiter')),
            ],
        ),
    ]
