# Generated by Django 2.1.5 on 2019-03-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_jobsbyrecruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='is_draft',
        ),
    ]
