# Generated by Django 2.1.5 on 2019-02-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name_id', models.IntegerField()),
                ('job_name', models.CharField(max_length=200)),
                ('job_name_slug', models.CharField(max_length=200)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JobCategory')),
            ],
        ),
    ]
