# Generated by Django 2.1.5 on 2019-02-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190212_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimarySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_skill_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('associated_to_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JobName')),
            ],
        ),
        migrations.CreateModel(
            name='SecondarySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_skill_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('associated_to_primary_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PrimarySkills')),
            ],
        ),
    ]
