# Generated by Django 2.1.5 on 2019-02-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_candidatefields_candidateskills_collegenames'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeneratedSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
