# Generated by Django 2.1.5 on 2019-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefields',
            name='candidate_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
