# Generated by Django 2.1.5 on 2019-02-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_candidatefields_candidate_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInterestedCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_city_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidatefields',
            name='current_location_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidatefields',
            name='remote_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateinterestedcities',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CandidateFields'),
        ),
    ]
