# Generated by Django 2.1.5 on 2019-02-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190217_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefields',
            name='resume_file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
