# Generated by Django 2.1.5 on 2019-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_candidatefields_resume_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefields',
            name='event_subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidatefields',
            name='newsletter_subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
