# Generated by Django 2.1.5 on 2019-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_candidatefields_welcome_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefields',
            name='onboarding_step_1_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidatefields',
            name='onboarding_step_2_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidatefields',
            name='onboarding_step_3_completed',
            field=models.BooleanField(default=True),
        ),
    ]
