# Generated by Django 2.1.5 on 2019-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleRecaptchaPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField()),
                ('page_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleRecaptchaSiteKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField()),
                ('secret_key', models.CharField(max_length=200)),
                ('site_key', models.CharField(max_length=200)),
            ],
        ),
    ]
